### ISSUE TITLE
Content.Load<Song> Gives a NullReferenceException

### ISSUE THREAD

**Issue by P-Storm** [FNA-XNA/FNA#191]
Hi all,

I'm trying to load a sound file (a mp3) in my game. The SoundEffect I can load this way.
```c#
            var song = Content.Load<Song>("Audio/Songs/song.mp3");
            MediaPlayer.Play(song);
```

And I get the following error:
```
Object reference not set to an instance of an object.
   at Vorbisfile.ov_info(IntPtr vf, Int32 link)
   at Microsoft.Xna.Framework.Media.Song..ctor(String fileName)
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
   at BeatBets.Game1.LoadContent()
   at Microsoft.Xna.Framework.Game.Initialize()
   at BeatBets.Game1.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at BeatBets.Program.Main(String[] args)
```

I'm using the newest fnalibs and FNA.

**Comment by flibitijibibo** [comment]
Only Ogg Vorbis is supported by FNA:

https://github.com/FNA-XNA/FNA/wiki/2:-Building-with-FNA#2b-rebuilding-wmawmv-files

**Comment by P-Storm** [comment]
Welp, skipped over that part! Thank you for your comment :)

**Comment by flibitijibibo** [comment]
If you happen to be proficient with C:

https://github.com/FNA-XNA/FAudio/issues/17
