### ISSUE TITLE
Exception when trying to load compiled XNB from a ResourceContentManager.

### ISSUE THREAD

**Issue by PumpkinPaul** [FNA-XNA/FNA#20]
Steps to reproduce...

1) Add a Resource file to project and add some compiled XNB to it "SomeTexture.xnb"

2) Load the content...
    var rcm = new ResourceContentManager(Services, Resource1.ResourceManager);
    rcm.Load<Texture2D>("SomeTexture");

The following exception is thrown...

An unhandled exception of type 'System.UnauthorizedAccessException' occurred in mscorlib.dll

Additional information: MemoryStream's internal buffer cannot be accessed.

mscorlib
   at System.IO.MemoryStream.GetBuffer()
   at Microsoft.Xna.Framework.Content.Texture2DReader.Read(ContentReader reader, Texture2D existingInstance) in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentReaders\Texture2DReader.cs:line 193
   at Microsoft.Xna.Framework.Content.ContentTypeReader`1.Read(ContentReader input, Object existingInstance) in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentTypeReader.cs:line 130
   at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance) in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentReader.cs:line 339
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T](T existingInstance) in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentReader.cs:line 153
   at Microsoft.Xna.Framework.Content.ContentReader.ReadObject[T]() in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentReader.cs:line 141
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]() in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentReader.cs:line 276
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentManager.cs:line 341
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Content\ContentManager.cs:line 214
   at FNATest.FNATestGame.LoadContent() in C:\Users\paul.cunningham\Source\Temp\FNATest\FNATest\FNATestGame.cs:line 24
   at Microsoft.Xna.Framework.Game.Initialize() in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Game.cs:line 725
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Game.cs:line 823
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\paul.cunningham\Source\_____Source\_____ThirdParty\FNA\src\Game.cs:line 438
   at FNATest.Program.Main(String[] args) in C:\Users\paul.cunningham\Source\Temp\FNATest\FNATest\Program.cs:line 8
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   
   
   
Potential Fix to ResourceContentManager.cs
------------------------------------------
   
```
protected override Stream OpenStream(string assetName)
{
	object obj = this.resource.GetObject(assetName);
	if (obj == null)
	{
		throw new ContentLoadException("Resource not found");
	}
	byte[] byteArrayObject = obj as byte[];
	if (byteArrayObject == null)
	{
		throw new ContentLoadException("Resource is not in binary format");
	}
	return new MemoryStream(byteArrayObject, 0, byteArrayObject.Length, true, true);
}
```

**Comment by flibitijibibo** [comment]
This is on .NET 4.5+, isn't it?

**Comment by flibitijibibo** [comment]
I knew it!

https://github.com/flibitijibibo/FNA-MGHistory/commit/ba19889d9601413d034119e5c46daa772fe59bd9

Anyway, this is fixed now:

https://github.com/FNA-XNA/FNA/commit/7c6daa8fa84021753336fb1cb4d7dde35c54dc0a

**Comment by PumpkinPaul** [comment]
Aye 4.6.1.
But it's ResourceContentManager giving me grief - have you patched it there too?

**Comment by flibitijibibo** [comment]
Yessir, it's the 100th commit to the repository that I pushed a couple minutes ago.

**Comment by PumpkinPaul** [comment]
Doh, sorry missed that second commit link! :-)
