### ISSUE TITLE
MacOS audio crashes

### ISSUE THREAD

**Issue by andreakarasho** [FNA-XNA/FNA#239]
Exception from my app:

```Microsoft.Xna.Framework.Audio.NoAudioHardwareException (0x80004005): External component has thrown an exception.
  at Microsoft.Xna.Framework.Audio.SoundEffect.Device () [0x0001e] in <9f6cee98428e4b9190db061c05e12cfe>:0 
  at Microsoft.Xna.Framework.Audio.SoundEffectInstance..ctor (Microsoft.Xna.Framework.Audio.SoundEffect parent) [0x00018] in <9f6cee98428e4b9190db061c05e12cfe>:0 
  at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance..ctor (System.Int32 sampleRate, Microsoft.Xna.Framework.Audio.AudioChannels channels) [0x00000] in <9f6cee98428e4b9190db061c05e12cfe>:0 
  at ClassicUO.IO.Audio.Sound.GetNewInstance (System.Boolean asEffect) [0x00022] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at ClassicUO.IO.Audio.Sound.Play (System.Boolean asEffect, ClassicUO.IO.Audio.AudioEffects effect, System.Single volume, System.Boolean spamCheck) [0x00035] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at ClassicUO.Game.Managers.AudioManager.PlayMusic (System.Int32 music) [0x000bb] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at ClassicUO.Game.Scenes.LoginScene.Load () [0x0010a] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at ClassicUO.Game.Scenes.SceneManager.ChangeScene (ClassicUO.Game.Scenes.ScenesType type) [0x00069] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at ClassicUO.Engine.LoadContent () [0x00000] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at Microsoft.Xna.Framework.Game.Initialize () [0x00053] in <9f6cee98428e4b9190db061c05e12cfe>:0 
  at ClassicUO.Engine.Initialize () [0x001c6] in <aa33287ef19844669ee5f4ecc1cda688>:0 
  at Microsoft.Xna.Framework.Game.DoInitialize () [0x0000d] in <9f6cee98428e4b9190db061c05e12cfe>:0 
  at Microsoft.Xna.Framework.Game.Run () [0x0000e] in <9f6cee98428e4b9190db061c05e12cfe>:0 
  at ClassicUO.Engine.Main (System.String[] args) [0x00023] in <aa33287ef19844669ee5f4ecc1cda688>:0 
```

**Comment by flibitijibibo** [comment]
Where’d the exception message go?

It’s probably because FAudio is missing or all your sound devices are disabled.

**Comment by andreakarasho** [comment]
`Where’d the exception message go?`
What do you mean?

- FAudio is loaded by the FNA.config file. Others libs are loaded in the same way.
- Audio is enabled

**Comment by flibitijibibo** [comment]
Usually a stack trace has a message, or at least a type - something like `NoAudioHardwareException`.

**Comment by andreakarasho** [comment]
Unfortunately i ve not a macos whre i can figure it out.
I tried to run an fna app from a vmware macos system, but it doesnt support 3d accelleration.
The report above is what the appdomani unhandled exception captures.

**Comment by flibitijibibo** [comment]
VMs aren’t supported, certainly not ones with software rendering.

Closing as “works on my machine” which includes a real Mac...

**Comment by andreakarasho** [comment]
Maybe i didnt explain well. The error is throw by a real mac. A guy sent to me report above, but i cannot replicate it cause i ve only a vm.
Anyway i hope to give to you more details

**Comment by SaschaKP** [comment]
same error on a windows machine:

Unhandled Exception: System.AccessViolationException: An attempt to read or write the protected memory. Often this condition indicates that other parts of the memory are damaged.
   at FAudio.FAudio_CreateSourceVoice(IntPtr audio, IntPtr& ppSourceVoice, FAudioWaveFormatEx& pSourceFormat, UInt32 Flags, Single MaxFrequencyRatio, IntPtr pCallback, IntPtr pSendList, IntPtr pEffectChain)
   at Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play()
   at Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.Play()

Audio card active and playing, but without any speaker connected, this crashes the game for good.
