### ISSUE TITLE
'GL error GL_INVALID_VALUE' exception thrown on game exit

### ISSUE THREAD

**Issue by boeotian** [FNA-XNA/FNA#308]
I don't know what the fuck is happening nor what info to provide so have this:
Can provide more if needed.

StackTrace:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=GL error GL_INVALID_VALUE
    Source: GL_DEBUG_SOURCE_API
    Type: GL_DEBUG_TYPE_ERROR
    Severity: GL_DEBUG_SEVERITY_HIGH
  Source=FNA
  StackTrace:
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.DebugCallback(GLenum source, GLenum type, UInt32 id, GLenum severity, Int32 length, IntPtr message, IntPtr userParam) in C:\CENSORED\FNA\src\FNAPlatform\OpenGLDevice_GL.cs:line 963
   at SDL2.SDL.SDL_GL_DeleteContext(IntPtr context)
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice.Dispose() in C:\CENSORED\FNA\src\FNAPlatform\OpenGLDevice.cs:line 903
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose(Boolean disposing) in C:\CENSORED\FNA\src\Graphics\GraphicsDevice.cs:line 506
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.Dispose() in C:\CENSORED\FNA\src\Graphics\GraphicsDevice.cs:line 473
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Dispose(Boolean disposing) in C:\CENSORED\FNA\src\GraphicsDeviceManager.cs:line 246
   at Microsoft.Xna.Framework.GraphicsDeviceManager.System.IDisposable.Dispose() in C:\CENSORED\FNA\src\GraphicsDeviceManager.cs:line 260
   at Microsoft.Xna.Framework.Game.Dispose(Boolean disposing) in C:\CENSORED\FNA\src\Game.cs:line 312
   at Microsoft.Xna.Framework.Game.Dispose() in C:\CENSORED\FNA\src\Game.cs:line 280
   at Client.Program.Main(String[] args) in C:\CENSORED\Client\Program.cs:line 89
```

Computer Information:
```
OS: Windows 10 Home (64 bit) 10.0.17134
Video Chipset: Intel HD Graphics Gen7 4EU
Video Chipset Codename: Valleyview
Video Memory: 2112 MBytes
Video Card: Intel Valleyview SoC - Integrated Graphics [C0] [Hewlett-Packard]
Video Bus: Integrated
Video RAMDAC: Internal
```

Driver Information:
```
Driver Manufacturer: Intel Corporation
Driver Description: Intel(R) HD Graphics
Driver Provider: Intel Corporation
Driver Version: 10.18.10.4885
Driver Date: 10-Dec-2017
DCH/UWD Driver: Not Capable
```

**Comment by flibitijibibo** [comment]
Your driver is 3 years old, are there any updates for it? You may also want to turn on native debugging so you can figure out exactly what GL (maybe WGL?) call is failing.

**Comment by boeotian** [comment]
Can't update the driver, throws up an empty dialog with yes/no buttons.. Far as I can tell the driver is fine, the error only occurs in this project.

Native debugging enabled: 
![image](https://user-images.githubusercontent.com/49934177/80621132-deca4b80-8a14-11ea-9c61-e47229feccad.png)

**Comment by flibitijibibo** [comment]
Looks like your driver has a spec violation in it somewhere - here's another example of the Intel Windows driver throwing errors in wglDeleteContext:

https://github.com/supertuxkart/stk-code/issues/2793

Not much we can do about this one, the Release version will not have this callback enabled so it's exclusive to debug builds. ANGLE is another possible workaround to look at.

**Comment by boeotian** [comment]
Well shit, thanks though.
