### ISSUE TITLE
Unable to load dll 'mojoshader' or one of its dependencies

### ISSUE THREAD

**Issue by Charanor** [FNA-XNA/FNA#326]
Hello! I keep getting this error whenever I try to run a freshly installed FNA project: `unable to load dll 'mojoshader' or one of its dependencies (MojoShader.cs:1274)`. Googling it finds me no solutions. What I've tried so far:

- Changing target framework (.NET Core 3.1, .NET Framework 4.0/4.5/some more)
- Installing Visual C++ Redistributable (I already have 2005-2015)
- Restarting computer - just in case 😶

How I created my project:

- I downloaded the FNA project files from the zip (I did not clone the project).
- I created a new solution and added the FNA project and linked it as dependency.
- I downloaded `fnalibs` and I use a post-build script to move the contents of `x64` to the `build\Debug\{framework}` folder, or to be exact: `xcopy /y /d "$(ProjectDir)fnalibs\x64\*.dll" "$(ProjectDir)$(OutDir)"`.
- I run the project using Jetbrains Rider IDE, or Visual Studio 2019 (neither works, same error) with .NET Core 3.1 (language version 8).

I'm on Windows 10.

Here is the full error, in case that's wanted:
```
System.DllNotFoundException: Unable to load DLL 'mojoshader' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at MojoShader.INTERNAL_glBestProfile(MOJOSHADER_glGetProcAddress lookup, IntPtr lookup_d, MOJOSHADER_malloc m, MOJOSHADER_free f, IntPtr malloc_d)
   at MojoShader.MOJOSHADER_glBestProfile(MOJOSHADER_glGetProcAddress lookup, IntPtr lookup_d, MOJOSHADER_malloc m, MOJOSHADER_free f, IntPtr malloc_d) in D:\Tools and Utilities\Programming\Libraries and extentions\FNA\lib\MojoShader\csharp\MojoShader.cs:line 1274
   at Microsoft.Xna.Framework.Graphics.OpenGLDevice..ctor(PresentationParameters presentationParameters) in D:\Tools and Utilities\Programming\Libraries and extentions\FNA\src\FNAPlatform\OpenGLDevice.cs:line 689
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateGLDevice(PresentationParameters presentationParameters, GraphicsAdapter adapter) in D:\Tools and Utilities\Programming\Libraries and extentions\FNA\src\FNAPlatform\SDL2_FNA
```

**Comment by flibitijibibo** [comment]
Try cloning FNA instead of using the zip - the fnalibs targets master and we just finished a major graphics rewrite.

**Comment by Charanor** [comment]
Awesome, now it works! I actually tried cloning after posting but I forgot `--recursive` so I guess it didn't work because of that.
