### ISSUE TITLE
Terraria: sigsegv when using vulkan renderer in newer versions of FNA

### ISSUE THREAD

**Issue by jafkc2** [FNA-XNA/FNA#458]
I get the error below when I start the game with /gldevice:Vulkan.
The problem seems to only happen with newer versions of FNA (23.9 and before works, 23.11 and 23.12 not). The FNA version that comes with Terraria launches the game without any problems.

I updated FNA with https://gist.github.com/flibitijibibo/f06e3f60eb66e5462da824e490229591.

error:

```Error Logging Enabled.
FNA3D Driver: Vulkan
Vulkan Device: Intel(R) HD Graphics (BDW GT1)
Vulkan Driver: Intel open-source Mesa driver Mesa 24.0.0-devel (git-f843b14c17)
Vulkan Conformance: 1.3.0
RGBA8 swapchain unsupported, falling back to BGRA8 with swizzle
Pipeline cache found, loading...
RGBA8 swapchain unsupported, falling back to BGRA8 with swizzle
Resolução alterada para: 1920x1080.

=================================================================
        Native Crash Reporting
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
        Native stacktrace:
=================================================================
        0x6ec4f2 - ./Terraria.bin.x86_64 : (null)
        0x6ec7ec - ./Terraria.bin.x86_64 : (null)
        0x6e84b9 - ./Terraria.bin.x86_64 : (null)
        0x69d836 - ./Terraria.bin.x86_64 : (null)

=================================================================
        Telemetry Dumper:
=================================================================
Pkilling 0x7f53d23fe6c0 from 0x7f5411ec4780
Pkilling 0x7f540ddff6c0 from 0x7f5411ec4780
Could not exec mono-hang-watchdog, expected on path '/usr/local/etc/../bin/mono-hang-watchdog' (errno 2)
Entering thread summarizer pause from 0x7f5411ec4780
Finished thread summarizer pause from 0x7f5411ec4780.

Waiting for dumping threads to resume

=================================================================
        External Debugger Dump:
=================================================================
[New LWP 22263]
[New LWP 22264]
[New LWP 22265]
[New LWP 22274]
[New LWP 22282]
[New LWP 22284]
[New LWP 22285]
[New LWP 22286]
[New LWP 22287]
[New LWP 22288]
[New LWP 22289]
[New LWP 22291]
[New LWP 22293]
[New LWP 22294]

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) [answered N; input not from terminal]
Debuginfod has been disabled.
To make this setting permanent, add 'set debuginfod enabled off' to .gdbinit.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007f5411a061c7 in wait4 () from /usr/lib/libc.so.6
  Id   Target Id                                           Frame 
* 1    Thread 0x7f5411ec4780 (LWP 22262) "Main Thread"     0x00007f5411a061c7 in wait4 () from /usr/lib/libc.so.6
  2    Thread 0x7f5410fff6c0 (LWP 22263) "SGen worker"     0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  3    Thread 0x7f540ddff6c0 (LWP 22264) "Finalizer"       0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  4    Thread 0x7f53fda7f6c0 (LWP 22265) "libusb_event"    0x00007f5411a0ef6f in poll () from /usr/lib/libc.so.6
  5    Thread 0x7f53ee9ff6c0 (LWP 22274) "Terrari:disk$0"  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  6    Thread 0x7f53ed3ff6c0 (LWP 22282) "Terrar:traceq0"  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  7    Thread 0x7f53e14866c0 (LWP 22284) "Terrari:disk$1"  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  8    Thread 0x7f53e0c856c0 (LWP 22285) "Terrari:disk$2"  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  9    Thread 0x7f53d3fff6c0 (LWP 22286) "Terrari:disk$3"  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  10   Thread 0x7f53ecbfe6c0 (LWP 22287) "WSI swapchain q" 0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  11   Thread 0x7f53f1a736c0 (LWP 22288) "PulseHotplug"    0x00007f5411a0f4c6 in ppoll () from /usr/lib/libc.so.6
  12   Thread 0x7f53d2bff6c0 (LWP 22289) "SDLAudioP2"      0x00007f5411a0f4c6 in ppoll () from /usr/lib/libc.so.6
  13   Thread 0x7f53d23fe6c0 (LWP 22291) "AsyncActionDisp" 0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
  14   Thread 0x7f53d0fff6c0 (LWP 22293) "SDLAudioP3"      0x00007f5411a0f4c6 in ppoll () from /usr/lib/libc.so.6
  15   Thread 0x7f53abfff6c0 (LWP 22294) "FACT Thread"     0x00007f54119e17f5 in clock_nanosleep () from /usr/lib/libc.so.6

Thread 15 (Thread 0x7f53abfff6c0 (LWP 22294) "FACT Thread"):
#0  0x00007f54119e17f5 in clock_nanosleep () from /usr/lib/libc.so.6
#1  0x00007f54119f38c7 in nanosleep () from /usr/lib/libc.so.6
#2  0x00007f53fdf8d196 in SDL_Delay_REAL () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#3  0x00007f53fca11ae6 in FACT_INTERNAL_APIThread () from /home/user/GOG Games/Terraria/game/lib64/libFAudio.so.0
#4  0x00007f53fdeba346 in SDL_RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#5  0x00007f53fdf855a9 in RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#6  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#7  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 14 (Thread 0x7f53d0fff6c0 (LWP 22293) "SDLAudioP3"):
#0  0x00007f5411a0f4c6 in ppoll () from /usr/lib/libc.so.6
#1  0x00007f53fbcc04f3 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#2  0x00007f53fbcca42c in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#3  0x00007f53fdf3ba55 in PULSEAUDIO_PlayDevice () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#4  0x00007f53fde2fcad in SDL_RunAudio () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#5  0x00007f53fdeba346 in SDL_RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#6  0x00007f53fdf855a9 in RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#7  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#8  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 13 (Thread 0x7f53d23fe6c0 (LWP 22291) "AsyncActionDisp"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x0000000000645d55 in mono_os_cond_timedwait ()
#3  0x00000000005e9230 in mono_w32handle_timedwait_signal_handle.constprop ()
#4  0x00000000005e985d in mono_w32handle_wait_one ()
#5  0x0000000000580b87 in ves_icall_System_Threading_Monitor_Monitor_wait ()
#6  0x000000000053b235 in ves_icall_System_Threading_Monitor_Monitor_wait_raw ()
#7  0x0000000040e0d3b3 in ?? ()
#8  0x00007f54111693a0 in ?? ()
#9  0xffffffffffffffff in ?? ()
#10 0x00007f5411168878 in ?? ()
#11 0xffffffffffffffff in ?? ()
#12 0x00007f5411168878 in ?? ()
#13 0x00007f53b40026a0 in ?? ()
#14 0x00007f53d23fd6e0 in ?? ()
#15 0x00007f53d23fd5c0 in ?? ()
#16 0xffffffff00000000 in ?? ()
#17 0xffffffffffffffff in ?? ()
#18 0xffffffffffffffff in ?? ()
#19 0xffffffffffffffff in ?? ()
#20 0x00000000022d2578 in ?? ()
#21 0x0000000000010000 in ?? ()
#22 0xffffffffffffffff in ?? ()
#23 0xffffffffffffffff in ?? ()
#24 0x00000000022d2578 in ?? ()
#25 0x0000000000010000 in ?? ()
#26 0xffffffffffffffff in ?? ()
#27 0xffffffffffffffff in ?? ()
#28 0x0000000040e0d330 in ?? ()
#29 0x000000000254a9a8 in ?? ()
#30 0x0000000040e0d21a in ?? ()
#31 0x00000000005cb3c0 in ?? ()
#32 0xffffffffffffffff in ?? ()
#33 0x00007f5411168878 in ?? ()
#34 0x00007f53d23fd6e0 in ?? ()
#35 0x0000000040e0d158 in ?? ()
#36 0x00007f5411168838 in ?? ()
#37 0x0000000000000000 in ?? ()

Thread 12 (Thread 0x7f53d2bff6c0 (LWP 22289) "SDLAudioP2"):
#0  0x00007f5411a0f4c6 in ppoll () from /usr/lib/libc.so.6
#1  0x00007f53fbcc04f3 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#2  0x00007f53fbcca42c in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#3  0x00007f53fdf3ba55 in PULSEAUDIO_PlayDevice () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#4  0x00007f53fde2fcad in SDL_RunAudio () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#5  0x00007f53fdeba346 in SDL_RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#6  0x00007f53fdf855a9 in RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#7  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#8  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 11 (Thread 0x7f53f1a736c0 (LWP 22288) "PulseHotplug"):
#0  0x00007f5411a0f4c6 in ppoll () from /usr/lib/libc.so.6
#1  0x00007f53fbcc04f3 in pa_mainloop_poll () from /usr/lib/libpulse.so.0
#2  0x00007f53fbcca42c in pa_mainloop_iterate () from /usr/lib/libpulse.so.0
#3  0x00007f53fbcca4e1 in pa_mainloop_run () from /usr/lib/libpulse.so.0
#4  0x00007f53fdf3bc8f in HotplugThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#5  0x00007f53fdeba346 in SDL_RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#6  0x00007f53fdf855a9 in RunThread () from /home/user/GOG Games/Terraria/game/lib64/libSDL2-2.0.so.0
#7  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#8  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 10 (Thread 0x7f53ecbfe6c0 (LWP 22287) "WSI swapchain q"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411998055 in pthread_cond_timedwait () from /usr/lib/libc.so.6
#2  0x00007f53ed54ae7d in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#3  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#4  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 9 (Thread 0x7f53d3fff6c0 (LWP 22286) "Terrari:disk$3"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f53ed6b4d9e in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#3  0x00007f53ed69f19c in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#4  0x00007f53ed6b4ccc in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#5  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#6  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 8 (Thread 0x7f53e0c856c0 (LWP 22285) "Terrari:disk$2"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f53ed6b4d9e in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#3  0x00007f53ed69f19c in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#4  0x00007f53ed6b4ccc in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#5  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#6  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 7 (Thread 0x7f53e14866c0 (LWP 22284) "Terrari:disk$1"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f53ed6b4d9e in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#3  0x00007f53ed69f19c in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#4  0x00007f53ed6b4ccc in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#5  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#6  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 6 (Thread 0x7f53ed3ff6c0 (LWP 22282) "Terrar:traceq0"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f53ed6b4d9e in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#3  0x00007f53ed69f19c in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#4  0x00007f53ed6b4ccc in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#5  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#6  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 5 (Thread 0x7f53ee9ff6c0 (LWP 22274) "Terrari:disk$0"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00007f53ed6b4d9e in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#3  0x00007f53ed69f19c in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#4  0x00007f53ed6b4ccc in ?? () from /usr/lib/libvulkan_intel_hasvk.so
#5  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#6  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7f53fda7f6c0 (LWP 22265) "libusb_event"):
#0  0x00007f5411a0ef6f in poll () from /usr/lib/libc.so.6
#1  0x00007f540c96aaa6 in ?? () from /usr/lib/libusb-1.0.so.0
#2  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#3  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7f540ddff6c0 (LWP 22264) "Finalizer"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f54119a0980 in ?? () from /usr/lib/libc.so.6
#2  0x0000000000515664 in finalizer_thread ()
#3  0x00000000005cdeb0 in start_wrapper ()
#4  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#5  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7f5410fff6c0 (LWP 22263) "SGen worker"):
#0  0x00007f54119954ae in ?? () from /usr/lib/libc.so.6
#1  0x00007f5411997d40 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x0000000000638903 in thread_func ()
#3  0x00007f54119989eb in ?? () from /usr/lib/libc.so.6
#4  0x00007f5411a1c7cc in ?? () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7f5411ec4780 (LWP 22262) "Main Thread"):
#0  0x00007f5411a061c7 in wait4 () from /usr/lib/libc.so.6
#1  0x00000000006ec641 in dump_native_stacktrace.isra ()
#2  0x00000000006ec7ec in mono_dump_native_crash_info ()
#3  0x00000000006e84b9 in mono_handle_native_crash ()
#4  0x000000000069d836 in altstack_handle_and_restore ()
#5  0x0000000000000000 in ?? ()
[Inferior 1 (process 22262) detached]

=================================================================
        Basic Fault Address Reporting
=================================================================
instruction pointer is NULL, skip dumping
=================================================================
        Managed Stacktrace:
=================================================================
          at <unknown> <0xffffffff>
          at Microsoft.Xna.Framework.Graphics.FNA3D:FNA3D_SetTextureName <0x000a1>
          at Microsoft.Xna.Framework.Graphics.FNA3D:FNA3D_SetTextureName <0x00047>
          at Microsoft.Xna.Framework.Graphics.Texture:set_Name <0x0007f>
          at Microsoft.Xna.Framework.Content.ContentManager:ReadAsset <0x00430>
          at InternalContentManager:Load <0x00047>
          at ReLogic.Content.Readers.XnbReader:FromStream <0x0009f>
          at ReLogic.Content.AssetReaderCollection:Read <0x000a5>
          at ReLogic.Content.AssetLoader:TryLoad <0x000bf>
          at ReLogic.Content.AssetRepository:TryLoadingAsset <0x001fa>
          at ReLogic.Content.AssetRepository:LoadAsset <0x000db>
          at ReLogic.Content.AssetRepository:Request <0x001e7>
          at Terraria.Initializers.AssetInitializer:LoadAsset <0x00062>
          at Terraria.Initializers.AssetInitializer:LoadSplashAssets <0x00033>
          at Terraria.Main:LoadContent <0x00657>
          at Microsoft.Xna.Framework.Game:Initialize <0x001ea>
          at Terraria.Main:Initialize <0x005c3>
          at Microsoft.Xna.Framework.Game:DoInitialize <0x00110>
          at Microsoft.Xna.Framework.Game:Run <0x0003b>
          at Terraria.Program:RunGame <0x001ef>
          at Terraria.Program:LaunchGame <0x00147>
          at Terraria.LinuxLaunch:Main <0x0011b>
          at <Module>:runtime_invoke_void_object <0x00085>
=================================================================
```

**Comment by flibitijibibo** [comment]
Looks like it's SetTextureName which should be a no-op for non-debug situations anyway... @kg

**Comment by jafkc2** [comment]
Your fix worked!! Thanks for the attention.
