### ISSUE TITLE
System.NullReferenceException when using BasicEffect

### ISSUE THREAD

**Issue by SuperErnD** [FNA-XNA/FNA#476]
just doing 
```cs
_effect = new BasicEffect(graphicsDevice); // graphicsDevice is provided by class constructor
```

and getting
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.Effect..ctor(GraphicsDevice graphicsDevice, Byte[] effectCode) in /home/diman/Документи/soxdxdxd/FNA/src/Graphics/Effect/Effect.cs:line 223
   at Microsoft.Xna.Framework.Graphics.BasicEffect..ctor(GraphicsDevice device) in /home/diman/Документи/soxdxdxd/FNA/src/Graphics/Effect/StockEffects/BasicEffect.cs:line 361
   at Chronical.FNARenderer..ctor(GraphicsDevice graphicsDevice) in /home/diman/Документи/soxdxdxd/Chronical/src/FNARenderer.cs:line 28
   at Chronical.ChronicalGame..ctor() in /home/diman/Документи/soxdxdxd/Chronical/src/Chronical.cs:line 96
   at Chronical.ChronicalGame.Main() in /home/diman/Документи/soxdxdxd/Chronical/src/Chronical.cs:line 29
```

**Comment by flibitijibibo** [comment]
GraphicsDevice probably isn't initialized yet if this is the Game constructor - try moving this call to LoadContent and see if that fixes it.

**Comment by SuperErnD** [comment]
now it works :D
thanks
